name: Build App Container Image and push to DockerHub

on:
  workflow_call:
    env:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_APP_NAME:
        required: true
    secrets:
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container image
        run: |
          docker build -f Dockerfile \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_APP_NAME }}:latest \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_APP_NAME }}:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_APP_NAME }} --all-tags