name: Build App Container Image and push to DockerHub

on:
  workflow_call:
    env:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_APP_NAME:
        required: true
      MONGO_DB:
        required: true
      MONGO_PORT:
        required: true
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      FLASK_SECRET_KEY:
        required: true
      MONGO_HOST:
        required: true
      MONGO_USERNAME:
        required: true
      MONGO_PASSWORD:
        required: true
  workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Add Production Environment Variables to Instance
        run: |
          cat << EOF > .env
          DEBUG="0"
          FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}
          MONGO_DB=${{ env.MONGO_DB }}
          MONGO_HOST=${{ secrets.MONGO_HOST }}
          MONGO_PORT=${{ env.PORT }}
          MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
          EOF
      - name: Build container image
        run: |
          docker build -f Dockerfile \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_APP_NAME }}:latest \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_APP_NAME }}:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_APP_NAME }} --all-tags